### ISSUE TITLE
sqlmap dbms not registering

### ISSUE THREAD

**Issue by obi-jon** [JGillam/burp-co2#17]
I am having an issue where even after selecting a specific db like mysql for the dbms field and having it register in the command line, that sqlmap presents a warning "using unescaped version of the test because of zero knowledge of the back-end DBMS. You can try to explicitly set it using option '--dbms'.  If I remove cookies then sqlmap registers that a dbms has been defined.

I am thinking that there is a character that is "hiding" the rest of the command.  Suggest at a minimum reordering the arguments to place --dbms and other arguments that are not likely to have unpredictable data to the front of the command line.

Example command line, as generated by CO2:

-u "http://www.REDACTED.com:80/sea?q=tired&Search=&t%5B%5D=60&t%5B%5D=59&t%5B%5D=20&t%5B%5D=17" --cookie="94d67bced54846a78374da8a9e1923d9=4r5p7c9rnen9u34p5kajrp1c00; __utma=219911813.1445517679.1465752379.1461003756.1451012151.7; __utmc=219911513; __utmz=219911813.1460752379.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); 3add0229b872e48831e0e4883c960c74=3vft7gcain5ifhqmndh77k0rr3; __utmb=219911813.6.10.1461012151; __utmt=1" --dbms="mysql"

**Comment by JGillam** [comment]
I think you are right but at a glance I don't see which character would be doing this (i.e. I don't see any extra quotes in the cookie).  Cookies seem to be problematic (they have in the past), wondering if maybe there's a newline or cr character sneaking in there somewhere.  A possible workaround may be to change the code so the cookies are always placed last... but that seems like a bandaid.  I'd really like to find out what the offending character is and handle it somehow.
