### ISSUE TITLE
send to sqlmapper removing the last character of the cookie.

### ISSUE THREAD

**Issue by jthorpe6** [JGillam/burp-co2#18]
Hi, forgive me if this is the wrong place to post this, but i noticed that the cookie value removes the last character from the request when selection to send to SQLMapper.

for example the following request    

```
GET /dvwa/vulnerabilities/sqli/?id=1&Submit=Submit HTTP/1.1
Host: 192.168.93.155
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://192.168.93.155/dvwa/vulnerabilities/sqli/
Cookie: security=low; PHPSESSID=m5m4pg0bq0qp3s2ner1vpo6kb3
DNT: 1
Connection: close
Upgrade-Insecure-Requests: 1
```

clearly the cookie is set to `Cookie: security=low; PHPSESSID=m5m4pg0bq0qp3s2ner1vpo6kb3` 

once right clicked and chosen to send to SQLMapper the cookie gets populated with the following  
`security=low;PHPSESSID=m5m4pg0bq0qp3s2ner1vpo6kb;` where it is missing the 3 at the end.

Thanks

**Comment by JGillam** [comment]
This seems strange... anyone else confirm it?  I haven't seen the issue.

**Comment by ngkogkos** [comment]
Just came here to open an issue for this :) I am not sure what is causing it. Adding more characters in the cookie then, resolves the issue. Could it be the size in specific?

**Comment by koxu1996** [comment]
I am experiencing same issue, last character is replaced whith semicolon. This is very annoying and makes this extension unuseful.

**Comment by spinkham** [comment]
I'm also having this issue.  Cookie length, content, or number all seem to make no difference: No matter what the input, the last character is always replaced by a semicolon.

Tested with both burp free and paid, 64 bit and 32 bit, and with version 1.7.26 and 1.7.19. 
CO2 was version 1.1.11

First noticed the issue in a VM, which you can download here if you wish: https://sourceforge.net/projects/websecuritydojo/files/latest/download

**Comment by spinkham** [comment]
Thought maybe it was line ending related, so tested on linux, mac and windows, seems the same on every platform with any request I throw at it.

**Comment by spinkham** [comment]
It deletes the last character because you tell it to. ;-)

```
if (cookies.length() > 1) {
  cookies.deleteCharAt(cookies.length() - 2);
}
```

Seems you used to add a semicolon and space to every cookie, then delete the last semicolon by deleting the 2nd to last cookie. Then 2 years ago you removed the spaces to fix issue #10, but still delete the 2nd to last character, which is now part of the cookie.

**Comment by spinkham** [comment]
Pull request #25 should fix this.

**Comment by JGillam** [comment]
Thanks @spinkham!
