### ISSUE TITLE
CeWLer doesnt support accents characters

### ISSUE THREAD

**Issue by cthulhu897** [JGillam/burp-co2#26]
CeWLer can't parse non-ASCII characters, which results in incomplete words and useless dictionaries on sites in which content is written in another language than English.

For example:
![image](https://user-images.githubusercontent.com/11900241/30713260-644d2bbc-9ed4-11e7-84d4-7c0e40abb5a4.png)
disposici --> disposición
distribu --> distribución

I think it would be useful to have another text box which lets users decide if they want to standardize output, like this way:
disposici --> disposicion
distribu --> distribucion

In cewl I work around this by setting the regex to something like `&[[:alpha:]]*;` and then I clean the words with  `unicodedata.normalize('NFKD', data).encode('ASCII', 'ignore')` but i cannot find the right way to do this with your extension.

Great extension by the way!

**Comment by cthulhu897** [comment]
Finally got it working!
Since I suck at Java and I dont know how to use Git, I couldn't do it the right way. So... I downloaded the latest JAR release, edited the regex that matches words and recompiled the class, then overwrote it within the latest relese.
The regex I used is:
`[a-zA-Z0-9'\p{L}]*`

And here is the file if anyone wants it:
[BurpCO2Suite_1.1.8b_mod_latin.zip](https://github.com/JGillam/burp-co2/files/1353543/BurpCO2Suite_1.1.8b_mod_latin.zip)
![image](https://user-images.githubusercontent.com/11900241/31144151-6a1dfeb6-a845-11e7-9747-e93872c0163f.png)

**Comment by JGillam** [comment]
Fixed in version 1.1.12
