### ISSUE TITLE
Risk level is 0

### ISSUE THREAD

**Issue by koxu1996** [JGillam/burp-co2#27]
I have to change risk level every time I send request to SQLMapper, because it is setted to 0:
![peek 2017-09-24 09-25](https://user-images.githubusercontent.com/6506780/30780415-76d9d978-a10a-11e7-9525-e46f3d7a2545.gif)

I would like to prepare pull request, but could you tell me how to load project in IntellijIDEA?

**Comment by JGillam** [comment]
Fixed in version 1.1.12
