### ISSUE TITLE
co2-all.jar identified as trojan by Bitdefender

### ISSUE THREAD

**Issue by axzhandul** [JGillam/burp-co2#33]
I've tried installing the CO2 extension in Burp Suite several times, and Bitdefender repeatedly identifies the co2-all.jar as a trojan: 

```
Threat successfully deleted.
Feature: Antivirus
An infected file attempted to run on your device.
Threat name: Trojan.Generic.32433175
Path: /Users/[USER]/.BurpSuite/bapps/c5071c7a7e004f72ae485e8a72911afc/build/libs/co2-all.jar
We deleted the file to prevent malicious commands from being executed on your device.
```

I checked the release notes and searched the entire repo and unless I'm missing it, I don't see any mention of this. To reproduce: 

1. Install Bitdefender Antivirus.
2. Install the CO2 extension in Burp. 

You can uninstall, reinstall repeatedly, same behavior. 

Any idea why this is? I have no problem with any other Burp Suite extensions. Would be nice to eliminate it if (presumably) it is a false positive. I look forward to your reply. 

Thx, axzhandul

**Comment by JGillam** [comment]
I'm working on this.  I suspect the issue is the embedded Laudanum code, which is a well-recognized web shell payload.

**Comment by axzhandul** [comment]
@JGillam hey thanks for the fix. I gave it a whirl -- the CO2 on the Portswigger BApp Store still pops the Bitdefender alert, same as before. But I pulled from the source here, built the jar, and loaded, and no problems, so looks like the fix did the trick. I don't know what's involved with getting the latest version of the code up to the BApp Store, but +1 for whatever it takes. Thanks!
