### ISSUE TITLE
SQLMapper Proxy Connection

### ISSUE THREAD

**Issue by kevcody** [JGillam/burp-co2#7]
Hello,

The Proxy Connection Tab in SQL Mapper is a great feature; however, it does not appear to utilize the proper syntax:

Example: --proxy=192.168.1.2:8080

This should be corrected to: --proxy='(http|https|socks4|socks5)://address:port'

Example: --proxy='https://192.168.1.2:8080'

Keep up the great work!

-kevcody

**Comment by JGillam** [comment]
I was able to get this to work by simply specifying the protocol and port in the field.  I'll add a tooltip on the field to provide the hint on the formatting.
