### ISSUE TITLE
Invalid usage of parameters when "Run" is pressed

### ISSUE THREAD

**Issue by Hipapheralkus** [JGillam/burp-co2#9]
I sent my HTTP request to CO2 SQLmapper. I set following options in GUI:
`--text-only -p "search" --dbms="mssql" --os="windows" --threads=1`
I configured path to sqlmap.py and pressed Run. However, I can see in CMD that it is ignoring parameters which I entered, because it is trying to use "PostgreSQL", "MySQL", and other technologies.
When I just copy+paste the same SQLMap command generated into another instance of SQLMap, it is working as expected and only MSSQL is used. Hence I guess that after pressing "Run", parameters are somehow not correctly propagated into the CMD window launched by Burp CO2.

**Comment by JGillam** [comment]
Which platform are you running on?  Windows?  I've recently tested this on OSX and Ubuntu.

**Comment by Hipapheralkus** [comment]
yes, Windows 8.1 Enterprise; Burp professional 1.6.30; CO2 1.1.8

**Comment by JGillam** [comment]
Anyone else still seeing this?  I can't seem to reproduce this issue.
